check_out_book/views/libraryinfo_view.py
from flask import Flask, Blueprint, render_template, session

bp = Blueprint('libraryinfo', __name__, url_prefix='/')

# 도서관 소개 html 호출
@bp.route('/libraryinfo')
def libraryinfo():
    return render_template('LibraryInfo.html')

check_out_book/views/main_view.py
import datetime

from dateutil.relativedelta import relativedelta
from flask import Blueprint, flash, render_template, request, session, url_for
from models import *
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')

# 최초 로딩 페이지, 메인 페이지(책목록)


@bp.route('/')
def home():
    page = request.args.get('page', type=int, default=1)
    book_list = Book.query.order_by(Book.id.asc())
    book_list = book_list.paginate(page, per_page=8)

    if '_flashes' in session:
        return render_template('Main.html', book_list=book_list, page=page)

    if 'email' in session:
        rentbook_list = CheckOutBook.query.filter_by(
            user_id=session['email']).all()

        for rentbook in rentbook_list:
            now = datetime.datetime.now()
            datenow = datetime.date(now.year, now.month, now.day)
            leftover = rentbook.end_date - datenow

            if 0 <= leftover.days <= 3:  # 반납 기간이 3일내로 들어왔을 때
                flash(rentbook.book_name+"의 반납 기간이 " +
                      str(leftover.days)+"일 남았습니다")

            if leftover.days < 0:  # 반납 기한 지나면
                flash(rentbook.book_name+"의 반납 기간이 지났습니다. 도서관으로 방문해서 반납해주세요!")

        return render_template('Main.html', book_list=book_list, rentbook_list=rentbook_list, page=page)
    return render_template('Main.html', book_list=book_list, page=page)

# 대여하기


@bp.route('/check_out/<int:book_id>', methods=('POST',))
def check_check_out(book_id):
    now = datetime.datetime.now()

    if request.method == 'POST':
        book = Book.query.filter_by(id=book_id).first()

        if 'email' not in session:
            flash("로그인 하십시오.")
            return redirect(url_for('main.home'))

        if book.stock < 1:
            flash("재고가 부족합니다.")
            return redirect(url_for('main.home'))

        rentbooknum = CheckOutBook.query.filter_by(
            user_id=session['email']).count()
        samerentbooknum = CheckOutBook.query.filter_by(
            book_id=book.id, user_id=session['email']).count()

        if samerentbooknum > 0:
            flash("이미 빌린 책입니다.")
            return redirect(url_for('main.home'))

        if rentbooknum > 4:  # 최대 5권 빌릴 수 있다고 가정
            flash("빌릴 수 있는 권수를 초과하였습니다")
            return redirect(url_for('main.home'))

        datenow = datetime.date(now.year, now.month, now.day)
        rentbooklist = CheckOutBook.query.filter_by(
            user_id=session['email']).all()
        count = 0
        stopdate = 0

        for rentbook in rentbooklist:
            leftover = rentbook.end_date - datenow
            print(leftover.days)
            if leftover.days < 0:
                print(leftover.days)
                stopdate += abs(leftover.days)
                print(stopdate)
                count += 1
        finalstopdate = stopdate * count

        if finalstopdate > 0:
            flash("연체반납이 일어나 "+str(finalstopdate) +
                  "일만큼 대출정지가 발생했습니다. 도서관 이용안내를 참고해주세요!")
            return redirect(url_for('main.home'))
        
        
        # 예약된 책이 있나 확인하고 없으면 예약(1번째 혼자 남았는데 연체나 권수를 초과하여 대기순번이 밀려 재고가 남았을 때)
        # 예약된 책이 있으면 - 만약 대출정지나 권수 초과로 대기순번 넘어가 있다가 나중에 빌릴때
        reservationbook = ReservationBook.query.filter_by(
            user_id=session['email'], book_id=book_id).first()
        print("예약된 책있냐!!!")
        print(reservationbook)
        if reservationbook is not None:
            flash("예약된 책이 대여되었습니다.")
            db.session.delete(reservationbook)
            db.session.commit()

        book.stock -= 1
        db.session.commit()
        end_date = now+relativedelta(weeks=2)
        check_out = CheckOutBook(book_id=book_id, book_name=book.book_name, book_link=book.link,
                                 user_id=session['email'], start_date=datetime.date(
                                     now.year, now.month, now.day),
                                 end_date=datetime.date(
                                     end_date.year, end_date.month, end_date.day),
                                 rating=book.rating)
        db.session.add(check_out)
        db.session.commit()
        flash("정상 처리되었습니다.")
        return redirect(url_for('main.home'))
        # return redirect("/../../"+"#"+str(book_id))

    return redirect(url_for('main.home'))

# 예약하기
@bp.route('/reservation/<int:book_id>', methods=('POST',))
def reservation(book_id):
    now = datetime.datetime.now()

    if request.method == 'POST':
        book = Book.query.filter_by(id=book_id).first()

        if 'email' not in session:
            flash("로그인 하십시오.")
            return redirect(url_for('main.home'))

        samerentbooknum = CheckOutBook.query.filter_by(
            user_id=session['email'], book_id=book.id).count()
        reservationbooknum = ReservationBook.query.filter_by(
            user_id=session['email']).count()
        samereservationbooknum = ReservationBook.query.filter_by(
            book_id=book.id, user_id=session['email']).count()

        if samerentbooknum > 0:
            flash("이미 빌린 책입니다.")
            return redirect(url_for('main.home'))

        if samereservationbooknum > 0:
            flash("이미 예약한 책입니다.")
            return redirect(url_for('main.home'))

        if reservationbooknum > 1:  # 최대 2권 예약할 수 있다고 가정
            flash("예약할 수 있는 권수를 초과하였습니다")
            return redirect(url_for('main.home'))

        booknum = ReservationBook.query.filter_by(book_id=book_id).count()
        booknum += 1
        reservationbook = ReservationBook(book_id=book_id, book_name=book.book_name,
                                          user_id=session['email'], create_time=datetime.date(
                                              now.year, now.month, now.day), book_link=book.link, book_num=booknum)
        db.session.add(reservationbook)
        db.session.commit()

        flash(str(booknum)+"번 째로 예약되었습니다.")

    return redirect(url_for('main.home'))

# 검색
@bp.route('/search', methods=('POST',))
def searchbook():
    book_name = request.form['keyword']
    print(book_name)
    search = "%{}%".format(book_name)
    print(search)
    searchbook_list = Book.query.filter(
        Book.book_name.like(search)).order_by(Book.id.asc())

    return render_template('SearchBook.html', searchbook_list=searchbook_list)

check_out_book/views/mypage_view.py
import datetime

from dateutil.relativedelta import relativedelta
from flask import Blueprint, Flask, flash, render_template, session, url_for
from models import *
from werkzeug.utils import redirect, secure_filename

bp = Blueprint("mypage", __name__, url_prefix="/")


# 예약한 책 목록
@bp.route("/reservation")
def reservationbook():
    reservationbook_list = ReservationBook.query.filter_by(
        user_id=session["email"]
    ).all()
    rentbook_list = CheckOutBook.query.filter_by(user_id=session["email"]).all()
    rentbooknum = CheckOutBook.query.filter_by(user_id=session["email"]).count()

    count = 0  # 연체반납한 책이 2권 이상일 때 flash가 두번이상 넘어가는거 방지
    for rentbook in rentbook_list:
        now = datetime.datetime.now()
        datenow = datetime.date(now.year, now.month, now.day)
        leftover = rentbook.end_date - datenow

        if leftover.days < 0:
            count += 1
    if count > 0:  # count가 한번이라도 일어나면
        flash("연체반납이 일어나 대기순번이 넘어갈 수 있습니다.")

    if rentbooknum > 4:  # 최대 5권 빌릴 수 있다고 가정
        flash("빌릴 수 있는 권수를 초과하여 대기순번이 넘어갈 수 있습니다.")
    return render_template("MyPage.html", reservationbook_list=reservationbook_list)


# 탈퇴하기
@bp.route("/withdraw", methods=("POST",))
def withdraw():
    user_review = (
        BookReview.query.filter_by(user_id=session["email"])
        .order_by(BookReview.book_id.asc())
        .all()
    )
    print(user_review)
    print(session["email"])
    # 리뷰 삭제

    for review in user_review:
        print(review.book_id)
        rate = Book.query.filter_by(id=review.book_id).first()
        ratenum = BookReview.query.filter_by(book_id=review.book_id).count()
        nowrate = rate.rating * ratenum - review.rating
        print(review.rating)
        if ratenum == 1:
            rate.rating = 0
        else:
            rate.rating = round(nowrate / (ratenum - 1), 1)
        print(rate.rating)
        CheckOutBook.query.filter_by(book_id=review.book_id).update(
            {"rating": rate.rating}
        )
        TotalCheckOutBook.query.filter_by(book_id=review.book_id).update(
            {"rating": rate.rating}
        )
        print(rate)
        db.session.delete(review)
        db.session.commit()
    # 대여한 책 삭제
    user_checkout = CheckOutBook.query.filter_by(user_id=session["email"]).all()
    print(user_checkout)

    for user in user_checkout:
        findbook = Book.query.filter_by(id=user.book_id).first()
        findbook.stock += 1
        db.session.commit()
        db.session.delete(user)
        db.session.commit()
        print(user)

    # 예약한 책 삭제
    user_reversation = ReservationBook.query.filter_by(user_id=session["email"]).all()
    print(user_reversation)

    for user in user_reversation:
        print("예약한 책 삭제")
        print(user)
        db.session.delete(user)
        db.session.commit()

    # 총 대여한 책 삭제
    user_totalcheckout = TotalCheckOutBook.query.filter_by(
        user_id=session["email"]
    ).all()
    print(user_totalcheckout)

    for user in user_totalcheckout:
        print("총 대여한 책")
        print(user)
        db.session.delete(user)
        db.session.commit()

    # 사용자 정보 삭제
    user = LibraryUser.query.filter_by(email=session["email"]).first()  # 조건 체크
    db.session.delete(user)
    db.session.commit()
    session.clear()
    flash("탈퇴되었습니다.")
    return redirect(url_for("main.home"))

check_out_book/views/returnbook_view.py
import datetime

from dateutil.relativedelta import relativedelta
from flask import Blueprint, flash, render_template, request, session, url_for
from models import *
from werkzeug.utils import redirect

bp = Blueprint("return", __name__, url_prefix="/return")


# 대여한 책목록
@bp.route("/booklist")
def returnbooklist():
    rentbook_list = CheckOutBook.query.filter_by(user_id=session["email"]).all()
    now = datetime.datetime.now()
    datenow = datetime.date(now.year, now.month, now.day)
    return render_template(
        "ReturnBook.html", rentbook_list=rentbook_list, datenow=datenow
    )


# 반납 시 재고가 0일때 예약 처리
def reservationreturn(book, findbook):

    now = datetime.datetime.now()
    findwholist = ReservationBook.query.filter_by(book_id=book.book_id).all()
    nowbooknum = 0

    for findwho in findwholist:
        print(findwho)
        rentbooknum = CheckOutBook.query.filter_by(user_id=findwho.user_id).count()
        print(rentbooknum)
        # 빌릴 수 있는 권수 초과면 넘어감
        if rentbooknum > 4:
            continue

        # 사용자의 대여기록을 통해 반납기한 지난 책 확인
        datenow = datetime.date(now.year, now.month, now.day)  # 현재날짜
        rentbooklist = CheckOutBook.query.filter_by(user_id=findwho.user_id).all()
        count = 0
        stopdate = 0

        for rentbook in rentbooklist:
            leftover = rentbook.end_date - datenow
            print(leftover.days)
            if leftover.days < 0:
                print(leftover.days)
                stopdate += abs(leftover.days)
                print(stopdate)
                count += 1
        finalstopdate = stopdate * count

        # 연체반납이 일어나면 넘어감
        if finalstopdate > 0:
            continue

        # 여기서 마이너스해도 returnbook 함수에서 +1해서 재고가 0이 됨
        findbook.stock -= 1
        db.session.commit()
        nowbooknum = findwho.book_num  # 현재 예약 성공한 사용자의 대기순번 저장

        # 위에 조건 2개 통과하면 대여함
        end_date = now + relativedelta(weeks=2)
        check_out = CheckOutBook(
            book_id=findbook.id,
            book_name=book.book_name,
            book_link=findbook.link,
            user_id=findwho.user_id,
            start_date=datetime.date(now.year, now.month, now.day),
            end_date=datetime.date(end_date.year, end_date.month, end_date.day),
            rating=findbook.rating,
        )

        db.session.delete(findwho)  # 해당하는 사람 예약 테이블에서 지우고
        db.session.add(check_out)
        db.session.commit()
        break

    # 다른 애들 순번 다 마이너스 1해주자~
    print("여기까지 옴")
    findwholist2 = ReservationBook.query.filter_by(book_id=book.book_id).all()

    for findwho in findwholist2:

        if len(findwholist2) != 1:  # 혼자 남은게 아니면
            print("findwho.book_num")
            print(findwho.book_num)
            print(nowbooknum)
            if nowbooknum < findwho.book_num:  # 예약받은 순번이 앞에 순번보다 높으면
                findwho.book_num -= 1  # 빼줌, 아니면 앞에 순번 유지시켜줘야함
                db.session.commit()


# 반납하기
@bp.route("/<int:pid>", methods=("POST",))
def returnbook(pid):
    print(pid)
    now = datetime.datetime.now()
    datenow = datetime.date(now.year, now.month, now.day)
    book = CheckOutBook.query.filter_by(id=pid).first()
    print(book)
    findbook = Book.query.filter_by(id=book.book_id).first()
    if findbook.stock == 0:  # 현재 재고가 0이면
        reservationreturn(book, findbook)  # 예약하기 함수 호출

    findbook.stock += 1
    db.session.commit()

    totalcheck_out = TotalCheckOutBook(
        book_id=book.book_id,
        user_id=session["email"],
        book_name=book.book_name,
        book_link=findbook.link,
        start_date=book.start_date,
        end_date=datenow,
        rating=book.rating,
    )
    db.session.add(totalcheck_out)
    db.session.delete(book)
    db.session.commit()
    flash("반납되었습니다.")
    return redirect(url_for("return.returnbooklist"))  # 함수명!!! main.함수명

check_out_book/views/totalcheckout_view.py
from flask import Blueprint, render_template, session
from models import *

bp = Blueprint("total", __name__, url_prefix="/total")

# 대여기록 목록
@bp.route("/checkout")
def checkout():
    totalrentbook_list = TotalCheckOutBook.query.filter_by(
        user_id=session["email"]
    ).all()
    return render_template("TotalCheckOut.html", totalrentbook_list=totalrentbook_list)

check_out_book/views/user_view.py
import re

from bcrypt import checkpw, gensalt, hashpw
from flask import Blueprint, flash, render_template, request, session, url_for
from models import *
from werkzeug.utils import redirect

bp = Blueprint("user", __name__, url_prefix="/")

# 회원가입 폼
@bp.route("/register")
def join():
    return render_template("Register.html")


# 회원가입 처리
@bp.route("/register", methods=("POST",))
def register():
    if request.method == "POST":
        user = LibraryUser.query.filter_by(email=request.form["email_id"]).first()

        if not (
            request.form["email_id"]
            or request.form["password2"]
            or request.form["password"]
            or request.form["name"]
        ):
            flash("모든 입력창을 채우세요")
            return redirect(url_for("user.register"))

        if not user:
            reg = re.compile("^[ㄱ-ㅎ|가-힣|a-z|A-Z|]+$")
            correctname = reg.match(request.form["name"])

            if correctname is None:
                flash("이름은 한글 또는 영어만 입력할 수 있습니다.")
                return redirect(url_for("user.register"))

            if request.form["password2"] != request.form["password"]:
                flash("비밀번호가 일치하지 않습니다")
                return redirect(url_for("user.register"))
                # \d = 숫자
            reg2 = re.compile(
                "^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$"
            )
            correctpw = reg2.match(request.form["password"])

            if correctpw is None:
                flash("비밀번호는 영문자, 숫자, 특수문자가 각각 한 개 이상, 총 8자리 이상이여야 합니다.")
                return redirect(url_for("user.register"))

            password = hashpw(request.form["password"].encode("utf-8"), gensalt())
            user = LibraryUser(
                email=request.form["email_id"],
                password=password,
                name=request.form["name"],
            )
            db.session.add(user)
            db.session.commit()
            flash("회원가입에 성공했습니다.")
            return redirect(url_for("main.home"))

        flash("이미 가입된 아이디입니다.")
        return redirect(url_for("user.register"))

    return redirect(url_for("user.register"))


# 로그인 폼
@bp.route("/login", methods=("GET",))
def login_try():
    return render_template("Login.html")


# 로그인 처리
@bp.route("/login", methods=("POST",))
def login():
    email = request.form["email"]
    password = request.form["password"]
    user_data = LibraryUser.query.filter_by(email=email).first()  # 조건 체크

    if not user_data:
        flash("존재하지 않는 아이디입니다.")
        return redirect(url_for("user.login_try"))

    if not checkpw(password.encode("utf-8"), user_data.password):
        flash("아이디와 비밀번호가 일치하지 않습니다.")
        return redirect(url_for("user.login_try"))

    if len(request.form["password"]) < 7:
        flash("비밀번호는 최소 8자리 이상 입력해야 합니다.")
        return redirect(url_for("user.login_try"))

    session.clear()
    session["email"] = email
    session["name"] = user_data.name
    flash("안녕하세요, {}님!".format(user_data.name))
    return redirect(url_for("main.home"))


# 로그아웃 처리
@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("main.home"))

check_out_book/templates/BaseSearch.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon" />
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.min.css') }}" />
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='my_styles.css') }}" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    <title>{% block title %}{% endblock %}</title>
</head>

<body>

    {% include "_navbar.html" %}
    {% include "Search.html" %}
    {% block content %}
    <div class="container2">  
            {%for message in get_flashed_messages() %}      
            {%if message=="탈퇴되었습니다."%}
            <div class="alert-withdraw">
                <div class="alert">
                    {{message}}
                </div>
            </div>
            {%else%}
            <div class="alert2">
                <div class="alert">
                    {{message}}
                </div>
            </div>
            {%endif%}
            {%endfor%}
        {% block page_content %}
        {% endblock %}
    </div>
    {% endblock %}
</body>

</html>

check_out_book/templates/MyPage.html
{% extends "Base.html" %}
{%block title%}마이페이지{%endblock%}
{% block page_content %}
<div class="libraryinfo">
    <p style="font-size:35px;font-weight:bold;padding-left: 5px;">마이페이지</p>
    {% if reservationbook_list %}
    <p style="margin-bottom:20px;font-size:25px;font-weight:bold;padding-left: 5px;"><i class="fas fa-book"></i> 예약기록</p>
    <div class="container">
    {% for book in reservationbook_list%}
    <div id={{book.book_id}} class="book-item">  
        <a style="text-decoration-line: none; color:black;" href="/detail/book/{{ book.book_id }}/12398978982">
            <img class="book-image" src=../{{book.book_link}}>
            <li class="book-list-item">{{ book.book_name }}
        </a>
        <p>예약날짜: {{book.create_time}}</p>
        <p>대기순번: {{book.book_num}}번</p>
            </li>
    </div>
    {% endfor %}   
</div>
{% else %}
<p class="nonebook"><i class="fas fa-book-open"></i>&nbsp;&nbsp;예약한 책이 없습니다.&nbsp;&nbsp;<i class="fas fa-book-open"></i></p>

{% endif %}
<p style="padding-top:20px;font-size:25px;font-weight:bold;padding-left: 5px;"><i class="fas fa-book"></i> 탈퇴하기</p>
<p style="padding-left: 20px;">- 탈퇴(계정삭제)하시려면 아래의  버튼을 눌러주세요.</p>
    <form action="{{ url_for('mypage.withdraw') }}" method="post">
        <input class="btn-withdraw" type="submit" value="탈퇴">
    </form>
</div>

{%endblock%}

check_out_book/templates/Search.html
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">

<form id="searchForm" action="{{ url_for('main.searchbook') }}" method="post">
    <nav class="navbar2">
        <div class="search">
            <input type="text" name="keyword" placeholder="검색어 입력">
            <button id="btn_search btn-success"><i class="fa fa-search" aria-hidden="true"></i></button>
        </div>
    </nav>
</form>

check_out_book/templates/_navbar.html
<nav class="navbar">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <a style="text-decoration-line: none; color:black; font-family: 'GongGothicBold', sans-serif;" class="nav-title"
        href="{{ url_for('main.home') }}"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="50" height="50" viewBox="0 0 226 226"
            style=" fill:#000000;">
            <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter"
                stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none"
                font-size="none" text-anchor="none" style="mix-blend-mode: normal">
                <path d="M0,226v-226h226v226z" fill="none"></path>
                <g fill="#000000">
                    <path
                        d="M112.92055,4.52c-0.70458,0.01077 -1.39688,0.18612 -2.02164,0.51203l-94.92,49.72c-1.48915,0.78194 -2.42103,2.32601 -2.41891,4.00797v13.56c0.00025,2.49622 2.02378,4.51975 4.52,4.52h9.04v9.04c0.00025,2.49622 2.02378,4.51975 4.52,4.52v81.36h-9.04c-2.49622,0.00025 -4.51975,2.02378 -4.52,4.52v9.04h-4.52c-2.49622,0.00025 -4.51975,2.02378 -4.52,4.52v13.56c0.00025,2.49622 2.02378,4.51975 4.52,4.52h198.88c2.49622,-0.00025 4.51975,-2.02378 4.52,-4.52v-13.56c-0.00025,-2.49622 -2.02378,-4.51975 -4.52,-4.52h-4.52v-9.04c-0.00025,-2.49622 -2.02378,-4.51975 -4.52,-4.52h-9.04v-81.36c2.49622,-0.00025 4.51975,-2.02378 4.52,-4.52v-9.04h9.04c2.49622,-0.00025 4.51975,-2.02378 4.52,-4.52v-13.56c0.00213,-1.68196 -0.92975,-3.22603 -2.41891,-4.00797l-94.92,-49.72c-0.67239,-0.3509 -1.42225,-0.52698 -2.18055,-0.51203zM113,14.15148l90.4,47.34524v6.30328h-144.64h-27.12h-9.04v-6.30328zM113,27.12c-9.93177,0 -18.08,8.14823 -18.08,18.08c0,9.93177 8.14823,18.08 18.08,18.08c9.93177,0 18.08,-8.14823 18.08,-18.08c0,-9.93177 -8.14823,-18.08 -18.08,-18.08zM113,36.16c5.04619,0 9.04,3.99381 9.04,9.04c0,5.04619 -3.99381,9.04 -9.04,9.04c-5.04619,0 -9.04,-3.99381 -9.04,-9.04c0,-5.04619 3.99381,-9.04 9.04,-9.04zM36.16,76.84h18.08v4.52h-18.08zM63.28,76.84h9.04v9.04c0.00025,2.49622 2.02378,4.51975 4.52,4.52v81.36h-18.08v-81.36c2.49622,-0.00025 4.51975,-2.02378 4.52,-4.52zM81.36,76.84h18.08v4.52h-18.08zM108.48,76.84h9.04v9.04c0.00025,2.49622 2.02378,4.51975 4.52,4.52v81.36h-18.08v-81.36c2.49622,-0.00025 4.51975,-2.02378 4.52,-4.52zM126.56,76.84h18.08v4.52h-18.08zM153.68,76.84h9.04v9.04c0.00025,2.49622 2.02378,4.51975 4.52,4.52v81.36h-18.08v-81.36c2.49622,-0.00025 4.51975,-2.02378 4.52,-4.52zM171.76,76.84h18.08v4.52h-18.08zM40.68,90.4h9.04v81.36h-9.04zM85.88,90.4h9.04v81.36h-9.04zM131.08,90.4h9.04v81.36h-9.04zM176.28,90.4h9.04v81.36h-9.04zM27.12,180.8h171.76v9.04c0.00025,2.49622 2.02378,4.51975 4.52,4.52h4.52v4.52h-189.84v-4.52h4.52c2.49622,-0.00025 4.51975,-2.02378 4.52,-4.52z">
                    </path>
                </g>
            </g>
        </svg> 도서관 대출</a>
    <nav class="nav-nav">
        {% if session['email'] %}

        <ul class="nav">

            <li class="nav-item">
                <a class="nav-link" href="{{url_for('mypage.reservationbook')}}">안녕하세요!
                    {{session['name']}}님</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('libraryinfo.libraryinfo')}}">도서관 소개</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('total.checkout')}}">대여기록</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('return.returnbooklist')}}">반납하기</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('user.logout')}}">로그아웃</a>
            </li>
        </ul>
        {% else %}
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('libraryinfo.libraryinfo')}}">도서관 소개</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{url_for('user.join')}}">회원가입</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('user.login')}}">로그인</a>
            </li>
        </ul>
        {%endif%}
    </nav>
</nav>

check_out_book/templates/login.html
{% extends "Base.html" %}
{% block page_content %}
<form action="{{ url_for('user.login') }}" method="post">
    <div class="register">
        <h2>로그인</h2>
    <div class="form-group2">
        <label for="email">아이디</label>
        <input class="form-control" type="email" name="email" id="email" placeholder="아이디 입력">
    </div>
    <div class="form-group2">
        <label for="password">비밀번호</label>
        <input class="form-control" name="password" type="password" placeholder="비밀번호 입력">
    </div>
    <input class="btn3 btn-success" type="submit" value="로그인">
</div>
</form>
{% endblock %}